version: "3.9"

services:
  ui:
    build:
      context: ../../ui/
      dockerfile: Dockerfile
    ports:
      - "8088:8000"
    env_file:
      - ../../.env-api
      - ../../.env-ui

  api:
    image: registry.gitlab.com/rarimo/polygonid/issuer-node:d16cbf843c81a6476363dc4ae911940c59c0b616
    ports:
      - "3001:3001"
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && migrate && platform"

  api-ui:
    image: omegatymbjiep/issuer-node:latest
    ports:
      - "3002:3002"
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && migrate && platform_ui"

  notifications:
    image: registry.gitlab.com/rarimo/polygonid/issuer-node:d16cbf843c81a6476363dc4ae911940c59c0b616
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && notifications"

  pending_publisher:
    image: registry.gitlab.com/rarimo/polygonid/issuer-node:d16cbf843c81a6476363dc4ae911940c59c0b616
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && pending_publisher"

  initializer:
    image: registry.gitlab.com/rarimo/polygonid/issuer-node:d16cbf843c81a6476363dc4ae911940c59c0b616
    env_file:
      - ../../.env-api
      - ../../.env-issuer
    command: sh -c "sleep 4s && migrate && issuer_initializer"

networks:
  default:
      name: issuer-network
