version: "3.9"
services:
  postgres:
    image: postgres:13.6
    hostname: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=polygonid
      - POSTGRES_PASSWORD=polygonid
      - POSTGRES_DB=platformid
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - platformid-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  test_postgres:
    image: postgres:14-alpine
    environment:
      - PGPORT=5435
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
    command: -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    ports:
      - "5435:5435"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6379", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  vault:
    image: vault:1.13.3
    volumes:
      - ./.vault/config:/vault/config
      - ./.vault/policies:/vault/policies
      - ./.vault/data:/vault/data
      - ./.vault/file:/vault/file:rw
      - ./.vault/scripts:/vault/scripts
      - ./.vault/plugins:/vault/plugins
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: ./vault/scripts/init.sh
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 2s
      timeout: 3s
      retries: 30

volumes:
  platformid-data:

networks:
  default:
      name: issuer-network
